name: Run Performance test on merge

on:
  push:
    branches:
      - main

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Terraform Repo
        uses: actions/checkout@v4
        with:
          repository: Ayon2016/TSC_Terraform_POC
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set Environment Variables for Terraform
        run: |
          echo "TF_VAR_aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan with Debugging
        run: TF_LOG=DEBUG terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve
