name: Run Performance test on merge

on:
  push: # change to pull_request
    branches:
      - main

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Terraform Repo
        uses: actions/checkout@v4
        with:
          repository: Ayon2016/TSC_Terraform_POC
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set Environment Variables for Terraform
        run: |
          echo "TF_VAR_aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan with Debugging
        run: TF_LOG=DEBUG terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get EC2 Public IPs
        run: |
          echo "LOCUST_MASTER_IP=$(terraform output -raw locust_master_public_ip)" >> $GITHUB_ENV
          echo "LOCUST_WORKER_IP=$(terraform output -raw locust_worker_public_ip)" >> $GITHUB_ENV

  setup-locust:
    needs: deploy-infra
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Locust Master
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.LOCUST_MASTER_IP }}
          username: bitnami # or ec2-user for Amazon Linux
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo apt update -y
            sudo apt install -y python3-pip
            pip3 install locust
            git clone https://github.com/Ayon2016/locust_test_framework.git ~/locust_test_framework
            cd locust_test_framework
            nohup locust -f locustfile.py --master

  cleanup:
    needs: setup-locust
    runs-on: ubuntu-latest
    if: always() # Ensures Terraform destroy runs even if previous steps fail

    steps:
      - name: Checkout Terraform Repo
        uses: actions/checkout@v3
        with:
          repository: Ayon2016/TSC_Terraform_POC

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
